#!/usr/bin/env python

#This script detects the informations about the piece to print, that will be sent to the php interface page

import time
import sys
import serial
import os
import signal
from datetime import datetime
from subprocess import PIPE, Popen


def cmdline(command):
        process = Popen(
                args=command,
                stdout=PIPE,
                shell=True
        )
        return process.communicate()[0]
    
    
def piece_informations():
    gfiles = cmdline("ls uploads/")
    
    #We first check if there is only one g-code file in uploads/
    gfiles_list = [str(i) for i in gfiles.split(b'\n')]
    gfiles_list.pop()
    
    
    if (len(gfiles_list) > 1):
        print("Multiple gcode files detected.")
        
    elif (len(gfiles_list) == 0):
        print("No gcode file detected.")
    
    #If there is only one file, we can extract the informations from it
    else:
        
        gfile_name = "uploads/" + gfiles_list[0][2:-1]
        
        gfile = open(gfile_name, "r")
        
        commands = [line.strip() for line in gfile]
        
        informations = ""
        
        for j in commands:
            if(j == ""):
                break
            elif(j[0] == ";"):
                #In g-code generated by Cura, the commentaries, in which we can find the informations about the piece, starts with an ";"
                informations = informations + j[1:] + "\n"
                
    print(informations)
                
piece_informations()